replicaCount: 1

image:
  repository: docker.io/guy66bp/hello-world-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000

ingress:
  enabled: true
  host: demo.yourdomain.com
  path: /

secrets:
  app_secret: "changeme"
